            - name: Deploy to Cloudflare Workers with Wrangler and get publish URL
  # You may pin to the exact commit or the version.
  # uses: buberdds/wrangler-action@ac7500fd25a20c905133ecbfa4d154e157676648
  uses: buberdds/wrangler-action@2.0.0
  with:
    # (Legacy) Your Cloudflare API Key
    apiKey: # optional
    # (Legacy) Your Cloudflare Email
    email: # optional
    # Your Cloudflare API Token
    apiToken: # optional
    # Your Cloudflare Account ID
    accountId: # optional
    # The environment you'd like to publish your Workers project to - must be defined in wrangler.toml
    environment: # optional
    # The relative path which Wrangler commands should be run from
    workingDirectory: # optional
    # The version of Wrangler you'd like to use to publish your Workers project
    wranglerVersion: # optional
    # A new line deliminated string of environment variable names that should be configured as Worker secrets
    secrets: # optional
    # Commands to execute before publishing the Workers project
    preCommands: # optional
    # Commands to execute after publishing the Workers project
    postCommands: # optional
    # The Wrangler command you wish to run. For example: "publish" - this will publish your Worker
    command: # optional
          
